import type { App } from 'vue'
import {
    CopyDocument,
    Check,
    Download,
    UploadFilled,
    Expand,
    Fold,
    CircleClose,
    Search,
    ArrowDown,
    ArrowUp,
    Refresh,
    Operation,
    UserFilled,
    Edit,
    User,
    Grid,
    PriceTag,
    SwitchButton,
    House,
    Plus,
    ScaleToOriginal,
    Delete,
    Clock,
    MostlyCloudy,
    InfoFilled,
    Upload,
    QuestionFilled,
    Lock,
    Memo,
    CirclePlusFilled,
    Remove,
    List,
    Setting,
    Bell,
    Share,
    Postcard,
    Aim,
    Tickets,
    Reading,
    ZoomIn,
    CircleCheck,
    HomeFilled,
    Menu,
} from '@element-plus/icons-vue'

const Icons = {
    CopyDocument,
    Check,
    Download,
    UploadFilled,
    Expand,
    Fold,
    CircleClose,
    Search,
    ArrowDown,
    ArrowUp,
    Refresh,
    Operation,
    UserFilled,
    Edit,
    User,
    Grid,
    PriceTag,
    SwitchButton,
    House,
    Plus,
    ScaleToOriginal,
    Delete,
    Clock,
    MostlyCloudy,
    InfoFilled,
    Upload,
    QuestionFilled,
    Lock,
    Memo,
    CirclePlusFilled,
    Remove,
    List,
    Setting,
    Bell,
    Share,
    Postcard,
    Aim,
    Tickets,
    Reading,
    ZoomIn,
    CircleCheck,
    HomeFilled,
    Menu,
}

export default function setupIcons (app: App) {
    Object.keys(Icons).forEach(key => {
        app.component(key, Icons[key as keyof typeof Icons])
    })
}
